### ISSUE TITLE
Remove the http service setting, `CreateTable` and `DropTable` uses grpc service

### ISSUE THREAD

**Issue by chunshao90** [CeresDB/ceresdb-client-java#33]
**Description**
CeresDB grpc service has already supported `CreateTable` and `DropTable`. 

**Proposal**
Remove the http service setting, `CreateTable` and `DropTable` uses grpc service.

**Additional context**

**Comment by mrrtree** [comment]
http service is removed, and `CreateTable` and `DropTable` uses grpc service in 1.0.0
